import { Composio } from "@composio/core";
import type { EndpointDefinition, EndpointReport, EndpointStatus, ParameterDef, TestReport } from "./types";

// ─── Internal types ───────────────────────────────────────────────────────────

type ContextStore = Map<string, string[]>;

type ProxyResult = {
  status: number;
  data?: unknown;
  headers?: Record<string, string>;
};

type RequestPayload = {
  resolvedPath: string;
  queryParameters: Array<{ in: "query"; name: string; value: unknown }>;
  body?: Record<string, unknown>;
};

type EndpointOutcome = {
  report: EndpointReport;
  rawResult: ProxyResult | null;
};

const MAX_IDS_PER_KEY = 5;

// ─── Utility: path parameter detection ───────────────────────────────────────

function detectPathParams(path: string): string[] {
  const matches: string[] = [];
  const re = /\{(\w+)\}/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(path)) !== null) matches.push(m[1]);
  return matches;
}

// ─── Utility: derive base resource name from a param name ────────────────────

function resourceNameFromParam(paramName: string): string {
  // e.g. "messageId" → "message", "event_id" → "event", "calendarKey" → "calendar"
  return paramName
    .replace(/Id$/i, "")
    .replace(/_id$/i, "")
    .replace(/Key$/i, "")
    .replace(/Name$/i, "")
    .toLowerCase();
}

// ─── Utility: singularize a word (naive — strip trailing "s") ────────────────

function singularize(word: string): string {
  if (word.endsWith("ies") && word.length > 4) return word.slice(0, -3) + "y"; // "calendaries"? unlikely
  if (word.endsWith("ses") && word.length > 4) return word.slice(0, -2);       // "messages" → "message"
  if (word.endsWith("s") && word.length > 2) return word.slice(0, -1);
  return word;
}

// ─── Utility: derive resource name from tool_slug ────────────────────────────

function deriveResourceFromSlug(toolSlug: string): string {
  // "GOOGLECALENDAR_CREATE_EVENT" → ["GOOGLECALENDAR","CREATE","EVENT"] → "event"
  const parts = toolSlug.split("_");
  return parts[parts.length - 1].toLowerCase();
}

// ─── Utility: generate a base64url-encoded RFC 2822 email ────────────────────

function generateBase64Email(): string {
  const raw = [
    "From: validator-test@example.com",
    "To: validator-test@example.com",
    "Subject: API Endpoint Validation Test",
    "MIME-Version: 1.0",
    "Content-Type: text/plain; charset=UTF-8",
    "",
    "This email was generated by the endpoint validator agent. Safe to delete.",
  ].join("\r\n");
  // btoa is available in Bun (global)
  return btoa(raw).replace(/\+/g, "-").replace(/\//g, "_").replace(/=/g, "");
}

// ─── Utility: construct a body field value from its definition ───────────────

function buildBodyField(field: ParameterDef): unknown {
  const name = field.name.toLowerCase();
  const desc = field.description.toLowerCase();
  const type = field.type.toLowerCase();

  if (type === "string") {
    if (desc.includes("rfc 2822") || name === "raw") return generateBase64Email();
    if (desc.includes("rfc3339") || desc.includes("datetime")) {
      return new Date(Date.now() + 86_400_000).toISOString();
    }
    return "test-value";
  }

  if (type === "integer" || type === "number") return 1;
  if (type === "boolean") return false;

  if (type === "object") {
    if (name === "start") {
      return { dateTime: new Date(Date.now() + 86_400_000).toISOString(), timeZone: "UTC" };
    }
    if (name === "end") {
      return { dateTime: new Date(Date.now() + 86_400_000 + 3_600_000).toISOString(), timeZone: "UTC" };
    }
    if (name === "message") {
      return { raw: generateBase64Email() };
    }
    return {};
  }

  return "test-value";
}

// ─── Improvement 1: LLM-assisted body construction via Groq ──────────────────
// Uses Groq's fast inference to generate valid request bodies from field metadata.
// Falls back to heuristic buildBodyField() if the API is unavailable or times out.

const GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions";
const GROQ_MODEL = "llama-3.1-8b-instant"; // fast + free tier

async function buildBodyWithLLM(endpoint: EndpointDefinition): Promise<Record<string, unknown> | null> {
  const groqKey = process.env.GROQ_API_KEY;
  if (!groqKey || !endpoint.parameters.body) return null;

  const tomorrow = new Date(Date.now() + 86_400_000).toISOString();
  const tomorrowPlusHour = new Date(Date.now() + 86_400_000 + 3_600_000).toISOString();
  const sampleEmail = generateBase64Email();

  const prompt = `You are an API testing assistant. Generate a minimal, valid JSON request body for this API endpoint.
Return ONLY a JSON object — no markdown fences, no explanation.

Endpoint: ${endpoint.method} ${endpoint.path}
Description: ${endpoint.description}
Fields:
${JSON.stringify(endpoint.parameters.body.fields, null, 2)}

Rules:
- For fields described as "RFC 2822" or named "raw": use exactly this base64url string: "${sampleEmail}"
- For fields described as "RFC3339" or "dateTime": use "${tomorrow}"
- For object fields named "start": use {"dateTime":"${tomorrow}","timeZone":"UTC"}
- For object fields named "end": use {"dateTime":"${tomorrowPlusHour}","timeZone":"UTC"}
- For object fields named "message": use {"raw":"${sampleEmail}"}
- For plain string fields: use "test-value"
- Keep all values safe and minimal — this is a validation test, not real usage

JSON body:`;

  try {
    const resp = await fetch(GROQ_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${groqKey}`,
      },
      body: JSON.stringify({
        model: GROQ_MODEL,
        messages: [{ role: "user", content: prompt }],
        temperature: 0,
        max_tokens: 400,
      }),
      signal: AbortSignal.timeout(8000), // 8 second timeout
    });

    if (!resp.ok) return null;

    const data = await resp.json() as { choices: Array<{ message: { content: string } }> };
    const raw = data.choices?.[0]?.message?.content?.trim() ?? "";

    // Extract first JSON object from response
    const match = raw.match(/\{[\s\S]*\}/);
    if (match) return JSON.parse(match[0]) as Record<string, unknown>;
  } catch {
    // Network error, timeout, or JSON parse failure — silently fall back
  }
  return null;
}

// ─── Utility: classify HTTP status into EndpointStatus ───────────────────────

function classifyResult(statusCode: number | null): EndpointStatus {
  if (statusCode === null) return "error";
  if (statusCode >= 200 && statusCode < 300) return "valid";
  if (statusCode === 401 || statusCode === 403) return "insufficient_scopes";
  if (statusCode === 404 || statusCode === 405) return "invalid_endpoint";
  return "error";
}

// ─── Utility: build a human-readable response summary ────────────────────────

function buildResponseSummary(
  endpoint: EndpointDefinition,
  statusCode: number | null,
  status: EndpointStatus,
  data: unknown,
  unresolvedParam: string | null
): string {
  if (unresolvedParam) {
    return `Required path parameter {${unresolvedParam}} could not be resolved from prior responses — endpoint not called to avoid a false invalid_endpoint classification.`;
  }
  if (statusCode === null) {
    return "Network error or exception — no HTTP response received. Classified as error.";
  }
  if (status === "valid") {
    const count = Array.isArray(data)
      ? data.length
      : typeof data === "object" && data !== null
      ? Object.keys(data).length
      : 0;
    return `Endpoint returned ${statusCode}. Response contains ${count > 0 ? count + " top-level fields" : "data"}.`;
  }
  if (status === "invalid_endpoint") {
    return `Endpoint returned ${statusCode} — the path or HTTP method does not exist in the real API.`;
  }
  if (status === "insufficient_scopes") {
    const scopes = endpoint.required_scopes.join(", ");
    return `Endpoint returned ${statusCode} Forbidden — connected account may lack required scope(s): ${scopes}.`;
  }
  return `Endpoint returned ${statusCode}. This may indicate a bad request body (400), server error (5xx), or other issue. Classified as error since the endpoint path itself may be valid.`;
}

// ─── Utility: truncate and redact response body ───────────────────────────────

function truncateResponseBody(data: unknown): unknown {
  if (data === null || data === undefined) return data;
  if (typeof data === "string") return data.length > 500 ? data.slice(0, 500) + "…" : data;

  if (Array.isArray(data)) {
    const truncated = data.slice(0, 3).map(truncateResponseBody);
    if (data.length > 3) return [...truncated, `…${data.length - 3} more items`];
    return truncated;
  }

  if (typeof data === "object") {
    const sensitiveKeys = new Set(["emailAddress", "email", "name", "displayName", "sender", "from", "to", "snippet"]);
    const result: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(data as Record<string, unknown>)) {
      if (sensitiveKeys.has(k)) {
        result[k] = "[redacted]";
      } else if (Array.isArray(v) && v.length > 3) {
        result[k] = [...v.slice(0, 3).map(truncateResponseBody), `…${v.length - 3} more`];
      } else {
        result[k] = truncateResponseBody(v);
      }
    }
    return result;
  }

  return data;
}

// ─── Build dependency graph (generic — no app-specific knowledge) ─────────────

function buildDependencyGraph(endpoints: EndpointDefinition[]): Map<string, string | null> {
  const depGraph = new Map<string, string | null>();

  for (const ep of endpoints) {
    const pathParams = detectPathParams(ep.path);

    if (pathParams.length === 0) {
      depGraph.set(ep.tool_slug, null);
      continue;
    }

    // Use the first path param to find a provider
    const paramName = pathParams[0];
    const resourceName = resourceNameFromParam(paramName);

    // Improvement 3: DELETE endpoints explicitly depend on a CREATE endpoint so the
    // ContextStore always has a freshly created ID available (avoids using a
    // real user resource and eliminates the GET vs DELETE race condition).
    if (ep.method === "DELETE") {
      const createProvider = endpoints.find((c) =>
        c.method === "POST" &&
        detectPathParams(c.path).length === 0 && // CREATE has no path params itself
        (c.tool_slug.toLowerCase().includes(resourceName) ||
          c.path.toLowerCase().includes("/" + resourceName))
      );
      if (createProvider) {
        depGraph.set(ep.tool_slug, createProvider.tool_slug);
        continue;
      }
    }

    // For all other endpoints with path params: find a GET list endpoint as provider
    const provider = endpoints.find((c) => {
      if (c.tool_slug === ep.tool_slug) return false;
      if (c.method !== "GET") return false;
      if (detectPathParams(c.path).length > 0) return false;
      const slugLower = c.tool_slug.toLowerCase();
      const pathLower = c.path.toLowerCase();
      const hasResource = slugLower.includes(resourceName) || pathLower.includes("/" + resourceName);
      const isList = slugLower.includes("list") || c.description.toLowerCase().includes("lists");
      return hasResource && isList;
    });

    depGraph.set(ep.tool_slug, provider?.tool_slug ?? null);
  }

  return depGraph;
}

// ─── Topological sort → execution waves (Kahn's BFS) ─────────────────────────

function topologicalSort(
  endpoints: EndpointDefinition[],
  depGraph: Map<string, string | null>
): EndpointDefinition[][] {
  const bySlug = new Map(endpoints.map((e) => [e.tool_slug, e]));
  const inDegree = new Map<string, number>();
  const dependents = new Map<string, string[]>(); // provider → list of endpoints that need it

  for (const ep of endpoints) {
    const dep = depGraph.get(ep.tool_slug) ?? null;
    inDegree.set(ep.tool_slug, dep ? 1 : 0);
    if (dep) {
      if (!dependents.has(dep)) dependents.set(dep, []);
      dependents.get(dep)!.push(ep.tool_slug);
    }
  }

  let queue = endpoints.filter((e) => inDegree.get(e.tool_slug) === 0);
  const waves: EndpointDefinition[][] = [];
  const processed = new Set<string>();

  while (queue.length > 0) {
    waves.push(queue);
    const nextQueue: EndpointDefinition[] = [];

    for (const ep of queue) {
      processed.add(ep.tool_slug);
      for (const depSlug of dependents.get(ep.tool_slug) ?? []) {
        const newDeg = (inDegree.get(depSlug) ?? 1) - 1;
        inDegree.set(depSlug, newDeg);
        if (newDeg === 0) {
          nextQueue.push(bySlug.get(depSlug)!);
        }
      }
    }

    queue = nextQueue;
  }

  // Handle any remaining endpoints (cycles or unresolved deps) — best effort
  const remaining = endpoints.filter((e) => !processed.has(e.tool_slug));
  if (remaining.length > 0) waves.push(remaining);

  return waves;
}

// ─── Normalize path for Composio proxy ───────────────────────────────────────
// Composio toolkit base URLs may already include an API version prefix.
// e.g. googlecalendar toolkit base = "https://www.googleapis.com/calendar/v3"
// so passing "/calendar/v3/calendars/..." doubles the prefix → 404.
// Strip the leading "/appname/vN" segment when it matches known Composio toolkits.

const COMPOSIO_STRIP_PREFIXES: RegExp[] = [
  /^\/calendar\/v\d+/,  // googlecalendar toolkit strips /calendar/v3
];

function normalizePathForComposio(path: string): string {
  for (const re of COMPOSIO_STRIP_PREFIXES) {
    if (re.test(path)) return path.replace(re, "");
  }
  return path;
}

// ─── Build request payload for an endpoint (async — uses LLM for body) ──────

async function buildRequest(
  endpoint: EndpointDefinition,
  store: ContextStore
): Promise<{ payload: RequestPayload; unresolvedParam: null } | { payload: null; unresolvedParam: string }> {
  let resolvedPath = normalizePathForComposio(endpoint.path);

  for (const paramName of detectPathParams(endpoint.path)) {
    // DELETE endpoints prefer freshly created resources to avoid racing with GET on the same ID
    const createdValues = endpoint.method === "DELETE"
      ? store.get("created_" + paramName) ?? null
      : null;

    const values =
      createdValues ??
      store.get(paramName) ??
      store.get(paramName.replace(/Id$/, "_id")) ??
      store.get(paramName.replace(/_id$/, "Id")) ??
      null;

    if (!values || values.length === 0) {
      return { payload: null, unresolvedParam: paramName };
    }

    resolvedPath = resolvedPath.replace(`{${paramName}}`, values[0]);
  }

  const queryParameters: RequestPayload["queryParameters"] = [];
  for (const qp of endpoint.parameters.query) {
    if (qp.name === "maxResults") {
      queryParameters.push({ in: "query", name: "maxResults", value: 5 });
    }
  }

  let body: Record<string, unknown> | undefined;
  if (["POST", "PUT", "PATCH"].includes(endpoint.method) && endpoint.parameters.body) {
    // Improvement 1: try LLM-assisted body construction first, fall back to heuristic
    const llmBody = await buildBodyWithLLM(endpoint);
    if (llmBody) {
      body = llmBody;
    } else {
      body = {};
      for (const field of endpoint.parameters.body.fields) {
        body[field.name] = buildBodyField(field);
      }
    }
  }

  return { payload: { resolvedPath, queryParameters, body }, unresolvedParam: null };
}

// ─── Extract IDs from a successful response → populate ContextStore ──────────

function extractIdsFromResponse(
  endpoint: EndpointDefinition,
  result: ProxyResult,
  store: ContextStore
): void {
  const data = result.data;
  if (!data || typeof data !== "object") return;

  const dataObj = data as Record<string, unknown>;

  // Case A: Scan top-level arrays for items with an "id" field
  for (const [key, value] of Object.entries(dataObj)) {
    if (!Array.isArray(value) || value.length === 0) continue;

    const ids = value
      .filter((item): item is Record<string, unknown> => !!item && typeof item === "object" && typeof item.id === "string")
      .map((item) => item.id as string)
      .slice(0, MAX_IDS_PER_KEY);

    if (ids.length === 0) continue;

    let resourceName = singularize(key); // "messages" → "message", "events" → "event"
    if (resourceName === "item") {
      // Generic "items" key — derive from endpoint slug then singularize
      // e.g. "GOOGLECALENDAR_LIST_EVENTS" → "events" → "event"
      resourceName = singularize(deriveResourceFromSlug(endpoint.tool_slug));
    }

    const camelKey = resourceName + "Id";
    const snakeKey = resourceName + "_id";

    const existingCamel = store.get(camelKey) ?? [];
    const existingSnake = store.get(snakeKey) ?? [];

    store.set(camelKey, [...existingCamel, ...ids].slice(0, MAX_IDS_PER_KEY));
    store.set(snakeKey, [...existingSnake, ...ids].slice(0, MAX_IDS_PER_KEY));
  }

  // Case B: Single-resource response (e.g. CREATE_EVENT returns { id: "..." })
  // Also store under "created_" prefix so DELETE endpoints can prefer freshly created resources
  if (typeof dataObj.id === "string") {
    const resourceName = singularize(deriveResourceFromSlug(endpoint.tool_slug));
    const camelKey = resourceName + "Id";
    const snakeKey = resourceName + "_id";
    const createdKey = "created_" + camelKey; // e.g. "created_eventId"

    const existingCamel = store.get(camelKey) ?? [];
    const existingSnake = store.get(snakeKey) ?? [];

    if (!existingCamel.includes(dataObj.id)) {
      store.set(camelKey, [...existingCamel, dataObj.id].slice(0, MAX_IDS_PER_KEY));
    }
    if (!existingSnake.includes(dataObj.id)) {
      store.set(snakeKey, [...existingSnake, dataObj.id].slice(0, MAX_IDS_PER_KEY));
    }
    // Always update the "created_" key with the latest created ID
    store.set(createdKey, [dataObj.id]);
  }
}

// ─── Improvement 2: proxyExecute with exponential backoff retry ──────────────
// Retries on 5xx responses or network exceptions. Gives transient server errors
// a chance to recover without misclassifying a real endpoint as "error".

type ProxyParams = {
  endpoint: string;
  method: string;
  connectedAccountId: string;
  parameters?: Array<{ in: "query"; name: string; value: unknown }>;
  body?: Record<string, unknown>;
};

async function proxyExecuteWithRetry(
  composio: Composio,
  params: ProxyParams,
  maxRetries = 2
): Promise<ProxyResult> {
  const proxyFn = composio.tools.proxyExecute as (p: ProxyParams) => Promise<ProxyResult>;
  let lastError: unknown;

  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    if (attempt > 0) {
      const delayMs = 1000 * Math.pow(2, attempt - 1); // 1 s, 2 s
      await new Promise((r) => setTimeout(r, delayMs));
    }

    try {
      const result = await proxyFn(params);
      // Retry on 5xx — server may be temporarily unavailable
      if (result.status >= 500 && attempt < maxRetries) {
        lastError = new Error(`HTTP ${result.status}`);
        continue;
      }
      return result;
    } catch (err) {
      lastError = err;
      // Only retry network/exception errors, not intentional API rejections
      if (attempt === maxRetries) throw err;
    }
  }

  throw lastError;
}

// ─── Test a single endpoint (the "one agent per endpoint" unit) ───────────────

async function testEndpoint(
  endpoint: EndpointDefinition,
  composio: Composio,
  connectedAccountId: string,
  store: ContextStore
): Promise<EndpointOutcome> {
  const { payload, unresolvedParam } = await buildRequest(endpoint, store);

  if (payload === null) {
    const report: EndpointReport = {
      tool_slug: endpoint.tool_slug,
      method: endpoint.method,
      path: endpoint.path,
      status: "error",
      http_status_code: null,
      response_summary: buildResponseSummary(endpoint, null, "error", null, unresolvedParam),
      response_body: null,
      required_scopes: endpoint.required_scopes,
      available_scopes: [],
    };
    return { report, rawResult: null };
  }

  let rawResult: ProxyResult | null = null;

  try {
    // Improvement 2: retry with exponential backoff on 5xx / network errors
    rawResult = await proxyExecuteWithRetry(composio, {
      endpoint: payload.resolvedPath,
      method: endpoint.method,
      connectedAccountId,
      ...(payload.queryParameters.length > 0 ? { parameters: payload.queryParameters } : {}),
      ...(payload.body !== undefined ? { body: payload.body } : {}),
    });
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    const report: EndpointReport = {
      tool_slug: endpoint.tool_slug,
      method: endpoint.method,
      path: endpoint.path,
      status: "error",
      http_status_code: null,
      response_summary: `Exception during proxyExecute: ${msg}`,
      response_body: msg,
      required_scopes: endpoint.required_scopes,
      available_scopes: [],
    };
    return { report, rawResult: null };
  }

  const status = classifyResult(rawResult.status);
  const report: EndpointReport = {
    tool_slug: endpoint.tool_slug,
    method: endpoint.method,
    path: endpoint.path,
    status,
    http_status_code: rawResult.status,
    response_summary: buildResponseSummary(endpoint, rawResult.status, status, rawResult.data, null),
    response_body: truncateResponseBody(rawResult.data),
    required_scopes: endpoint.required_scopes,
    available_scopes: status === "valid" ? endpoint.required_scopes : [],
  };

  return { report, rawResult };
}

// ─── Main orchestrator ────────────────────────────────────────────────────────

// ─── Resolve real connected account IDs (SDK requires ca_xxx, not entity ID) ──

async function resolveAccountIdMap(
  composio: Composio,
  entityId: string
): Promise<Map<string, string>> {
  const map = new Map<string, string>(); // toolkit_slug → connected account id
  try {
    const result = await (composio.connectedAccounts as unknown as {
      list: (q: { entityId: string }) => Promise<{ items: Array<{ id: string; status: string; toolkit: { slug: string } }> }>;
    }).list({ entityId });
    for (const acc of result.items) {
      if (acc.status === "ACTIVE" && !map.has(acc.toolkit.slug)) {
        map.set(acc.toolkit.slug, acc.id);
      }
    }
  } catch {
    // If lookup fails, fall back to using entityId directly
  }
  return map;
}

function resolveConnectedAccountId(
  endpoint: EndpointDefinition,
  accountMap: Map<string, string>,
  fallback: string
): string {
  // Detect app slug from the endpoint path prefix
  const path = endpoint.path.toLowerCase();
  for (const [slug, id] of accountMap) {
    // Match /gmail/ → "gmail", /calendar/ → "googlecalendar"
    const shortSlug = slug.replace("google", ""); // "googlecalendar" → "calendar"
    if (path.includes("/" + slug + "/") || path.includes("/" + shortSlug + "/")) {
      return id;
    }
  }
  return fallback;
}

export async function runAgent(params: {
  composio: Composio;
  connectedAccountId: string;
  endpoints: EndpointDefinition[];
}): Promise<TestReport> {
  const { composio, connectedAccountId, endpoints } = params;

  console.log("  [agent] Resolving connected account IDs...");
  const accountMap = await resolveAccountIdMap(composio, connectedAccountId);
  if (accountMap.size > 0) {
    console.log(`  [agent] Found ${accountMap.size} active connection(s): ${[...accountMap.entries()].map(([k, v]) => `${k}=${v}`).join(", ")}`);
  } else {
    console.log("  [agent] No active connections found via lookup — using entity ID directly");
  }

  console.log("  [agent] Building dependency graph...");
  const depGraph = buildDependencyGraph(endpoints);

  console.log("  [agent] Sorting into execution waves...");
  const waves = topologicalSort(endpoints, depGraph);

  console.log(`  [agent] ${waves.length} wave(s) detected:`);
  waves.forEach((wave, i) => {
    console.log(`    Wave ${i}: ${wave.map((e) => e.tool_slug).join(", ")}`);
  });

  const store: ContextStore = new Map();
  const results: EndpointReport[] = [];

  for (let i = 0; i < waves.length; i++) {
    const wave = waves[i];
    console.log(`\n  [agent] Executing Wave ${i} (${wave.length} endpoints in parallel)...`);

    const outcomes = await Promise.all(
      wave.map((ep) => {
        const accountId = resolveConnectedAccountId(ep, accountMap, connectedAccountId);
        return testEndpoint(ep, composio, accountId, store);
      })
    );

    // Orchestrator updates the shared store after the wave completes (thread-safe)
    for (let j = 0; j < wave.length; j++) {
      const { report, rawResult } = outcomes[j];
      console.log(`    [${report.status.padEnd(20)}] ${report.tool_slug} (HTTP ${report.http_status_code ?? "—"})`);

      if (report.status === "valid" && rawResult) {
        extractIdsFromResponse(wave[j], rawResult, store);
      }

      results.push(report);
    }
  }

  console.log(`\n  [agent] ContextStore after all waves: ${[...store.keys()].join(", ") || "(empty)"}`);

  const summary = {
    valid: 0,
    invalid_endpoint: 0,
    insufficient_scopes: 0,
    error: 0,
  };
  for (const r of results) summary[r.status]++;

  return {
    timestamp: new Date().toISOString(),
    total_endpoints: endpoints.length,
    results,
    summary,
  };
}
